#!/bin/bash
if test "ruby -v | grep 'ruby 2.*'"; then
	echo "Ruby >= v2.0.....Ok"
else
	echo "Ruby >= v2.0.....No"
	echo "This script may encounter error(s)."
fi

gems=(rest-client activesupport json commander)

for i in `seq 0 3`;
do
        if test "$(gem list | grep ${gems[i]})"; then
                echo "${gems[i]} Ok."
        else
                echo "${gems[i]} not found, installing."
                gem install ${gems[i]}
        fi
done

#if $(cd /home/$USER/veracodecli); then
#	echo 'Scripts Ok.'
#else
#	$(cd /home/$USER; git clone https://github.com/isand3r/veracodecli.git)
#fi

PATH=$PATH:/home/$USER/veracodecli/bin
#export USERNAME=""
#export PASSWORD=""

git archive --format=tar latest_commit.tar master
/home/$USER/veracodecli/bin/veracodecli scan $HOSTNAME latest_commit.tar --trace
rm -r latest_commit.tar
